open Asn.S
open Asn_grammars

(* This type really conflates three things: the set of pk algos that describe
 * the public key, the set of hashes, and the set of hash+pk algo combinations
 * that describe digests. The three are conflated because they are generated by
 * the same ASN grammar, AlgorithmIdentifier, to keep things close to the
 * standards.
 *
 * It's expected that downstream code with pick a subset and add a catch-all
 * that handles unsupported algos anyway.
 *)

type ec_curve =
  [ `SECP256R1 | `SECP384R1 | `SECP521R1 ]

let ec_curve_to_string = function
  | `SECP256R1 -> "SECP256R1"
  | `SECP384R1 -> "SECP384R1"
  | `SECP521R1 -> "SECP521R1"

type t =

  (* pk algos *)
  (* any more? is the universe big enough? ramsey's theorem for pk cyphers? *)
  | RSA
  | EC_pub of ec_curve

  (* sig algos *)
  | MD5_RSA
  | SHA1_RSA
  | SHA256_RSA
  | SHA384_RSA
  | SHA512_RSA
  | SHA224_RSA
  | ECDSA_SHA1
  | ECDSA_SHA224
  | ECDSA_SHA256
  | ECDSA_SHA384
  | ECDSA_SHA512

  | ED25519

  (* digest algorithms *)
  | MD5
  | SHA1
  | SHA256
  | SHA384
  | SHA512
  | SHA224

  (* HMAC algorithms *)
  | HMAC_SHA1
  | HMAC_SHA224
  | HMAC_SHA256
  | HMAC_SHA384
  | HMAC_SHA512

  (* symmetric block ciphers *)
  | AES128_CBC of string
  | AES192_CBC of string
  | AES256_CBC of string

  (* PBE encryption algorithms *)
  | SHA_RC4_128 of string * int
  | SHA_RC4_40 of string * int
  | SHA_3DES_CBC of string * int
  | SHA_2DES_CBC of string * int
  | SHA_RC2_128_CBC of string * int
  | SHA_RC2_40_CBC of string * int

  | PBKDF2 of string * int * int option * t
  | PBES2 of t * t

let to_string = function
  | RSA -> "RSA"
  | EC_pub curve -> ec_curve_to_string curve
  | MD5_RSA -> "RSA MD5"
  | SHA1_RSA -> "RSA SHA1"
  | SHA256_RSA -> "RSA SHA256"
  | SHA384_RSA -> "RSA SHA384"
  | SHA512_RSA -> "RSA SHA512"
  | SHA224_RSA -> "RSA SHA224"
  | ECDSA_SHA1 -> "ECDSA SHA1"
  | ECDSA_SHA224 -> "ECDSA SHA224"
  | ECDSA_SHA256 -> "ECDSA SHA256"
  | ECDSA_SHA384 -> "ECDSA SHA384"
  | ECDSA_SHA512 -> "ECDSA SHA512"
  | ED25519 -> "Ed25519"
  | MD5 -> "MD5"
  | SHA1 -> "SHA1"
  | SHA256 -> "SHA256"
  | SHA384 -> "SHA384"
  | SHA512 -> "SHA512"
  | SHA224 -> "SHA224"
  | HMAC_SHA1 -> "HMAC SHA1"
  | HMAC_SHA224 -> "HMAC SHA224"
  | HMAC_SHA256 -> "HMAC SHA256"
  | HMAC_SHA384 -> "HMAC SHA384"
  | HMAC_SHA512 -> "HMAC SHA512"
  | AES128_CBC _ -> "AES128 CBC"
  | AES192_CBC _ -> "AES192 CBC"
  | AES256_CBC _ -> "AES256 CBC"
  | SHA_RC4_128 (_, _) -> "PBES: SHA RC4 128"
  | SHA_RC4_40 (_, _) -> "PBES: SHA RC4 40"
  | SHA_3DES_CBC (_, _) -> "PBES: SHA 3DES CBC"
  | SHA_2DES_CBC (_, _) -> "PBES: SHA 2DES CBC"
  | SHA_RC2_128_CBC (_, _) -> "PBES: SHA RC2 128"
  | SHA_RC2_40_CBC (_, _) -> "PBES: SHA RC2 40"
  | PBKDF2 (_, _, _, _) -> "PBKDF2"
  | PBES2 (_, _) -> "PBES2"

let to_hash = function
  | MD5    -> Some `MD5
  | SHA1   -> Some `SHA1
  | SHA224 -> Some `SHA224
  | SHA256 -> Some `SHA256
  | SHA384 -> Some `SHA384
  | SHA512 -> Some `SHA512
  | _      -> None

and of_hash = function
  | `MD5    -> MD5
  | `SHA1   -> SHA1
  | `SHA224 -> SHA224
  | `SHA256 -> SHA256
  | `SHA384 -> SHA384
  | `SHA512 -> SHA512

and to_hmac = function
  | HMAC_SHA1 -> Some `SHA1
  | HMAC_SHA224 -> Some `SHA224
  | HMAC_SHA256 -> Some `SHA256
  | HMAC_SHA384 -> Some `SHA384
  | HMAC_SHA512 -> Some `SHA512
  | _ -> None

and of_hmac = function
  | `SHA1   -> HMAC_SHA1
  | `SHA224 -> HMAC_SHA224
  | `SHA256 -> HMAC_SHA256
  | `SHA384 -> HMAC_SHA384
  | `SHA512 -> HMAC_SHA512

and to_key_type = function
  | RSA        -> Some `RSA
  | EC_pub curve -> Some (`EC curve)
  | ED25519    -> Some `ED25519
  | _          -> None

and of_key_type = function
  | `RSA    -> RSA
  | `EC curve -> EC_pub curve
  | `ED25519 -> ED25519

and to_signature_algorithm = function
  | MD5_RSA -> Some (`RSA_PKCS1, `MD5)
  | SHA1_RSA -> Some (`RSA_PKCS1, `SHA1)
  | SHA256_RSA -> Some (`RSA_PKCS1, `SHA256)
  | SHA384_RSA -> Some (`RSA_PKCS1, `SHA384)
  | SHA512_RSA -> Some (`RSA_PKCS1, `SHA512)
  | SHA224_RSA -> Some (`RSA_PKCS1, `SHA224)
  | ECDSA_SHA1 -> Some (`ECDSA, `SHA1)
  | ECDSA_SHA224 -> Some (`ECDSA, `SHA224)
  | ECDSA_SHA256 -> Some (`ECDSA, `SHA256)
  | ECDSA_SHA384 -> Some (`ECDSA, `SHA384)
  | ECDSA_SHA512 -> Some (`ECDSA, `SHA512)
  | ED25519 -> Some (`ED25519, `SHA512)
  | _ -> None

and of_signature_algorithm public_key_algorithm digest =
  match public_key_algorithm, digest with
  | (`RSA_PKCS1, `MD5) -> MD5_RSA
  | (`RSA_PKCS1, `SHA1) -> SHA1_RSA
  | (`RSA_PKCS1, `SHA256) -> SHA256_RSA
  | (`RSA_PKCS1, `SHA384) -> SHA384_RSA
  | (`RSA_PKCS1, `SHA512) -> SHA512_RSA
  | (`RSA_PKCS1, `SHA224) -> SHA224_RSA
  | (`ECDSA, `SHA1)   -> ECDSA_SHA1
  | (`ECDSA, `SHA224) -> ECDSA_SHA224
  | (`ECDSA, `SHA256) -> ECDSA_SHA256
  | (`ECDSA, `SHA384) -> ECDSA_SHA384
  | (`ECDSA, `SHA512) -> ECDSA_SHA512
  | (`ED25519, _) -> ED25519
  | _ -> failwith "unsupported signature scheme and hash"

(* RSA signature identifiers accept both absent and NULL parameters, whereas
   rsaEncryption (the RSA public-key algorithm) requires NULL, per RFC 3279
   section 2.3.1. The legacy [identifier] encoder normalizes RSA signatures;
   [Identifier] preserves their parameter presence and the OIW SHA1 alias. *)

let curve_of_oid, curve_to_oid =
  let open Registry.ANSI_X9_62 in
  (let default oid = Asn.(S.parse_error "Unknown algorithm %a" OID.pp oid) in
   case_of_oid ~default [
     (secp256r1, `SECP256R1) ;
     (secp384r1, `SECP384R1) ;
     (secp521r1, `SECP521R1) ;
   ]),
  (function
    | `SECP256R1 -> secp256r1
    | `SECP384R1 -> secp384r1
    | `SECP521R1 -> secp521r1)

type 'a parameter_data = [
  | `PBE of string * int
  | `PBKDF2 of string * int * int option * 'a
  | `PBES2 of 'a * 'a
]

type 'a parameters = [
  | `C1 of unit | `C2 of Asn.oid | `C3 of 'a parameter_data | `C4 of string
]

let (algorithm_of_parameters, parameters_of_algorithm) :
  (Asn.oid * t parameters option -> t) *
  (t -> Asn.oid * t parameters option) =
  let open Registry in

  let f =
    let none x = function
      | None -> x
      | _    -> parse_error "Algorithm: expected no parameters"
    and null x = function
      | Some (`C1 ()) -> x
      | _             -> parse_error "Algorithm: expected null parameters"
    and null_or_none x = function
      | None | Some (`C1 ()) -> x
      | _                    -> parse_error "Algorithm: expected null or none parameter"
    and oid f = function
      | Some (`C2 id) -> f id
      | _             -> parse_error "Algorithm: expected parameter OID"
    and pbe f = function
      | Some (`C3 `PBE pbe) -> f pbe
      | _                   -> parse_error "Algorithm: expected parameter PBE"
    and pbkdf2 f = function
      | Some (`C3 `PBKDF2 params) -> f params
      | _                         -> parse_error "Algorithm: expected parameter PBKDF2"
    and pbes2 f = function
      | Some (`C3 `PBES2 params) -> f params
      | _                        -> parse_error "Algorithm: expected parameter PBES2"
    and octets f = function
      | Some (`C4 salt) -> f salt
      | _               -> parse_error "Algorithm: expected parameter octet_string"
    and default oid = Asn.(S.parse_error "Unknown algorithm %a" OID.pp oid)
    in

    case_of_oid_f ~default [

      (ANSI_X9_62.ec_pub_key, oid (fun id -> EC_pub (curve_of_oid id))) ;

      (PKCS1.rsa_encryption          , null RSA                  ) ;
      (PKCS1.md5_rsa_encryption      , null_or_none MD5_RSA      ) ;
      (PKCS1.sha1_rsa_encryption     , null_or_none SHA1_RSA     ) ;
      (sha1_rsa_encryption           , null_or_none SHA1_RSA     ) ;
      (PKCS1.sha256_rsa_encryption   , null_or_none SHA256_RSA   ) ;
      (PKCS1.sha384_rsa_encryption   , null_or_none SHA384_RSA   ) ;
      (PKCS1.sha512_rsa_encryption   , null_or_none SHA512_RSA   ) ;
      (PKCS1.sha224_rsa_encryption   , null_or_none SHA224_RSA   ) ;

      (ANSI_X9_62.ecdsa_sha1         , none ECDSA_SHA1   ) ;
      (ANSI_X9_62.ecdsa_sha224       , none ECDSA_SHA224 ) ;
      (ANSI_X9_62.ecdsa_sha256       , none ECDSA_SHA256 ) ;
      (ANSI_X9_62.ecdsa_sha384       , none ECDSA_SHA384 ) ;
      (ANSI_X9_62.ecdsa_sha512       , none ECDSA_SHA512 ) ;

      (RFC8410.ed25519               , none ED25519 ) ;

      (md5                           , null MD5          ) ;
      (sha1                          , null SHA1         ) ;
      (sha256                        , null SHA256       ) ;
      (sha384                        , null SHA384       ) ;
      (sha512                        , null SHA512       ) ;
      (sha224                        , null SHA224       ) ;

      (PKCS2.hmac_sha1               , null HMAC_SHA1    );
      (PKCS2.hmac_sha224             , null HMAC_SHA224  );
      (PKCS2.hmac_sha256             , null HMAC_SHA256  );
      (PKCS2.hmac_sha384             , null HMAC_SHA384  );
      (PKCS2.hmac_sha512             , null HMAC_SHA512  );

      (PKCS5.aes128_cbc              , octets (fun iv -> AES128_CBC iv));
      (PKCS5.aes192_cbc              , octets (fun iv -> AES192_CBC iv));
      (PKCS5.aes256_cbc              , octets (fun iv -> AES256_CBC iv));

      (PKCS12.pbe_with_SHA_and_128Bit_RC4, pbe (fun (s, i) -> SHA_RC4_128 (s, i))) ;
      (PKCS12.pbe_with_SHA_and_40Bit_RC4, pbe (fun (s, i) -> SHA_RC4_40 (s, i))) ;
      (PKCS12.pbe_with_SHA_and_3_KeyTripleDES_CBC, pbe (fun (s, i) -> SHA_3DES_CBC (s, i))) ;
      (PKCS12.pbe_with_SHA_and_2_KeyTripleDES_CBC, pbe (fun (s, i) -> SHA_2DES_CBC (s, i))) ;
      (PKCS12.pbe_with_SHA_and_128Bit_RC2_CBC, pbe (fun (s, i) -> SHA_RC2_128_CBC (s, i))) ;
      (PKCS12.pbe_with_SHA_and_40Bit_RC2_CBC, pbe (fun (s, i) -> SHA_RC2_40_CBC (s, i))) ;

      (PKCS5.pbkdf2, pbkdf2 (fun (s, i, l, m) -> PBKDF2 (s, i, l, m))) ;
      (PKCS5.pbes2, pbes2 (fun (oid, oid') -> PBES2 (oid, oid')))
    ]

  and g =
    let none    = None
    and null    = Some (`C1 ())
    and oid  id = Some (`C2 id)
    and pbe (s, i) = Some (`C3 (`PBE (s, i)))
    and pbkdf2 (s, i, k, m) = Some (`C3 (`PBKDF2 (s, i, k, m)))
    and pbes2 (oid, oid') = Some (`C3 (`PBES2 (oid, oid')))
    and octets data = Some (`C4 data)
    in
    function
    | EC_pub id     -> (ANSI_X9_62.ec_pub_key , oid (curve_to_oid id))

    | RSA           -> (PKCS1.rsa_encryption           , null)
    | MD5_RSA       -> (PKCS1.md5_rsa_encryption       , null)
    | SHA1_RSA      -> (PKCS1.sha1_rsa_encryption      , null)
    | SHA256_RSA    -> (PKCS1.sha256_rsa_encryption    , null)
    | SHA384_RSA    -> (PKCS1.sha384_rsa_encryption    , null)
    | SHA512_RSA    -> (PKCS1.sha512_rsa_encryption    , null)
    | SHA224_RSA    -> (PKCS1.sha224_rsa_encryption    , null)

    | ECDSA_SHA1    -> (ANSI_X9_62.ecdsa_sha1          , none)
    | ECDSA_SHA224  -> (ANSI_X9_62.ecdsa_sha224        , none)
    | ECDSA_SHA256  -> (ANSI_X9_62.ecdsa_sha256        , none)
    | ECDSA_SHA384  -> (ANSI_X9_62.ecdsa_sha384        , none)
    | ECDSA_SHA512  -> (ANSI_X9_62.ecdsa_sha512        , none)

    | ED25519       -> (RFC8410.ed25519                , none)

    | MD5           -> (md5                            , null)
    | SHA1          -> (sha1                           , null)
    | SHA256        -> (sha256                         , null)
    | SHA384        -> (sha384                         , null)
    | SHA512        -> (sha512                         , null)
    | SHA224        -> (sha224                         , null)

    | HMAC_SHA1     -> (PKCS2.hmac_sha1                , null)
    | HMAC_SHA224   -> (PKCS2.hmac_sha224              , null)
    | HMAC_SHA256   -> (PKCS2.hmac_sha256              , null)
    | HMAC_SHA384   -> (PKCS2.hmac_sha384              , null)
    | HMAC_SHA512   -> (PKCS2.hmac_sha512              , null)

    | AES128_CBC iv -> (PKCS5.aes128_cbc               , octets iv)
    | AES192_CBC iv -> (PKCS5.aes192_cbc               , octets iv)
    | AES256_CBC iv -> (PKCS5.aes256_cbc               , octets iv)

    | SHA_RC4_128 (s, i) -> (PKCS12.pbe_with_SHA_and_128Bit_RC4, pbe (s, i))
    | SHA_RC4_40 (s, i) -> (PKCS12.pbe_with_SHA_and_40Bit_RC4, pbe (s, i))
    | SHA_3DES_CBC (s, i) -> (PKCS12.pbe_with_SHA_and_3_KeyTripleDES_CBC, pbe (s, i))
    | SHA_2DES_CBC (s, i) -> (PKCS12.pbe_with_SHA_and_2_KeyTripleDES_CBC, pbe (s, i))
    | SHA_RC2_128_CBC (s, i) -> (PKCS12.pbe_with_SHA_and_128Bit_RC2_CBC, pbe (s, i))
    | SHA_RC2_40_CBC (s, i) -> (PKCS12.pbe_with_SHA_and_40Bit_RC2_CBC, pbe (s, i))

    | PBKDF2 (s, i, k, m) -> (PKCS5.pbkdf2, pbkdf2 (s, i, k, m))
    | PBES2 (oid, oid') -> (PKCS5.pbes2, pbes2 (oid, oid'))
  in
  f, g

let map_parameter_algorithms (f : 'a -> 'b) : 'a parameters option -> 'b parameters option = function
  | Some (`C3 (`PBKDF2 (salt, count, length, prf))) ->
    Some (`C3 (`PBKDF2 (salt, count, length, f prf)))
  | Some (`C3 (`PBES2 (kdf, cipher))) ->
    Some (`C3 (`PBES2 (f kdf, f cipher)))
  | Some (`C3 (`PBE params)) -> Some (`C3 (`PBE params))
  | Some (`C1 ()) -> Some (`C1 ())
  | Some (`C2 oid) -> Some (`C2 oid)
  | Some (`C4 octets) -> Some (`C4 octets)
  | None -> None

let identifier_syntax id =
  let pbkdf2_or_pbe_or_pbes2_params =
    (* This shared legacy grammar does not support PBKDF2 saltSources, a key
       length, or an omitted default PRF. These are not certificate algorithms.
       [Identifier.of_algorithm] rejects a key length instead of erasing it. *)
    let f = function
      | `C1 salt, Some count, None -> `PBE (salt, count)
      | `C1 salt, Some count, Some prf -> `PBKDF2 (salt, count, None, prf)
      | `C2 oid, None, Some oid' -> `PBES2 (oid, oid')
      | _ -> parse_error "bad parameters"
    and g = function
      | `PBE (salt, count) -> (`C1 salt, Some count, None)
      | `PBKDF2 (salt, count, _key_len, prf) -> (`C1 salt, Some count, Some prf)
      | `PBES2 (oid, oid') -> (`C2 oid, None, Some oid')
    in
    map f g @@
    sequence3
      (required ~label:"salt" (choice2 octet_string id))
      (optional ~label:"iteration count" int)
      (optional ~label:"prf" id)
  in
  sequence2
    (required ~label:"algorithm" oid)
    (optional ~label:"params"
       (choice4 null oid pbkdf2_or_pbe_or_pbes2_params octet_string))

module Identifier : sig
  type algorithm = t
  type t

  (** Uses conventional OIDs and parameters, including NULL for RSA signatures.
      Like the legacy grammar, PBKDF2 only supports an octet-string salt, an
      explicit PRF and no key length. A non-[None] PBKDF2 key length raises
      [Invalid_argument], including in nested algorithms. *)
  val of_algorithm : algorithm -> t

  val algorithm : t -> algorithm

  (** Semantic equality: ignores parameter presence and OID aliases. *)
  val equivalent : t -> t -> bool

  val asn : t Asn.t
  val encode_der : t -> string
  val decode_der : string -> (t, [> `Msg of string ]) result
end = struct
  type algorithm = t

  (* Algorithm parameters live in [algorithm], not in a DER cache. Only the
     choices erased by the semantic projection are retained here, recursively
     for PBKDF2 and PBES2. [Conventional] also covers conventional subtrees. *)
  type encoding =
    | Conventional
    | Rsa_signature of { null_parameters : bool; oiw_sha1 : bool }
    | Pbkdf2 of encoding
    | Pbes2 of encoding * encoding

  type t = { algorithm : algorithm; encoding : encoding }

  let rec check_algorithm = function
    | PBKDF2 (_, _, Some _, _) ->
      invalid_arg "Algorithm.Identifier: PBKDF2 key length is unsupported"
    | PBKDF2 (_, _, None, prf) -> check_algorithm prf
    | PBES2 (kdf, cipher) -> check_algorithm kdf; check_algorithm cipher
    | _ -> ()

  let of_algorithm algorithm =
    check_algorithm algorithm;
    { algorithm; encoding = Conventional }

  let algorithm t = t.algorithm
  let equivalent a b = a.algorithm = b.algorithm

  let of_parameters (oid, params) =
    let algorithm = algorithm_of_parameters (oid, map_parameter_algorithms algorithm params) in
    let encoding = match algorithm, params with
      | (MD5_RSA | SHA1_RSA | SHA224_RSA | SHA256_RSA | SHA384_RSA | SHA512_RSA), _ ->
        Rsa_signature {
          null_parameters = Option.is_some params;
          oiw_sha1 = Asn.OID.equal oid Registry.sha1_rsa_encryption;
        }
      | PBKDF2 _, Some (`C3 (`PBKDF2 (_, _, _, prf))) -> Pbkdf2 prf.encoding
      | PBES2 _, Some (`C3 (`PBES2 (kdf, cipher))) -> Pbes2 (kdf.encoding, cipher.encoding)
      | _ -> Conventional
    in
    { algorithm; encoding }

  let to_parameters t =
    let oid, params = parameters_of_algorithm t.algorithm in
    match t.encoding, params with
    | Conventional, _ -> oid, map_parameter_algorithms of_algorithm params
    | Rsa_signature { null_parameters; oiw_sha1 }, _ ->
      (if oiw_sha1 then Registry.sha1_rsa_encryption else oid),
      (if null_parameters then Some (`C1 ()) else None)
    | Pbkdf2 encoding, Some (`C3 (`PBKDF2 (salt, count, length, prf))) ->
      oid, Some (`C3 (`PBKDF2 (salt, count, length, { algorithm = prf; encoding })))
    | Pbes2 (kdf_encoding, cipher_encoding), Some (`C3 (`PBES2 (kdf, cipher))) ->
      oid, Some (`C3 (`PBES2
        ({ algorithm = kdf; encoding = kdf_encoding },
         { algorithm = cipher; encoding = cipher_encoding })))
    | _ -> assert false

  let asn = fix (fun id -> map of_parameters to_parameters (identifier_syntax id))
  let of_der, encode_der = projections_of Asn.der asn
  let decode_der der = err_to_msg (of_der der)
end

(* Legacy callers are a semantic view of the same recursive grammar. Sharing
   its fixpoint also avoids comparing distinct function keys in Asn's cache. *)
let identifier = map Identifier.algorithm Identifier.of_algorithm Identifier.asn

let ecdsa_sig =
  sequence2
    (required ~label:"r" unsigned_integer)
    (required ~label:"s" unsigned_integer)

let ecdsa_sig_of_octets, ecdsa_sig_to_octets =
  projections_of Asn.der ecdsa_sig

let pp fmt x = Fmt.string fmt (to_string x)
